
# This is a basic workflow that is manually triggered

name: CHANGELOG_AUTOGEN

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
   pull_request:
    types:
      - closed
    branches:
      - master
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
 build: 
 # The type of runner that the job will run on
  runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
  steps:

    - name: Print generating changelog
      run: echo "Generating new CHANGELOG"   
      
    # Checkout the branch
    - name: checkout
      uses: actions/checkout@v3
      with:
         fetch-depth: 0
         token: ${{ github.token }}
      
    - name: Append Changelog
      run: 
         git log origin/main >> CHANGELOG.md
         
    - name: Commit CHANGELOG  
      run: |        
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add .
            git commit -m "generated"
            git push
