
# This is a basic workflow that is manually triggered

name: CHANGELOG_AUTOGEN

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
   pull_request:
    branches:
      - master
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
 build: 
 # The type of runner that the job will run on
  runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
  steps:
    # Runs a single command using the runners shell
    - name: Print generating changelog
      run: echo "Generating new CHANGELOG"
    - name: Append Changelog
      run: git log  ${{ github.base_ref }} --pretty=format:"%h %ad | %s %d" --date=short >> CHANGELOG.md
           git config user.name github-actions
           git config user.email github-actions@github.com
           git add .
           git commit -m "generated"
